In [1]:
import numpy as np 
import cv2 
import os 
from matplotlib import pyplot as plt 
from sklearn.gaussian_process import GaussianProcessRegressor 
from sklearn.gaussian_process.kernels import DotProduct, WhiteKernel
from skimage import io, img_as_float 
import imquality.brisque as brisque

In [2]:
img = cv2.imread("Image/bad1.png", 0) #if u pass in 1 as 2nd argument it gives original image and 0 gives greyscale image 
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()
# cv2.imwrite("Image/test.png", img) #create a new file but the openCV environemnt changes the encoding so the size of these files are different

In [3]:
type(img)
len(img)

368

In [ ]:
black = np.zeros([500, 200, 1], 'uint8')
cv2.imshow("Black", black)
print(black[0,0:])
cv2.waitKey(0)
cv2.destroyAllWindows()

# Variance Code to seperate Good and Bad Images 

In [6]:
img = img_as_float(io.imread('Image/bad1.png', as_gray=True))

print(img.var())
# print(score)

0.010859245666450683


In [9]:
li = ["bad1", "bad2", "good3", "good4","good5","good6","good7","good8"]
for i in li: 
    img = img_as_float(io.imread('Image/'+ i + '.png', as_gray=True))
    print(img.var())
#0.002 as the threshold for differentiating good and bad images 

0.010859245666450683
0.003700628557076839
6.344487567988743e-05
7.722142677156263e-05
0.0011284648811054365
0.0011071940174921368
6.901009376203697e-05
0.0011125890157333285


In [4]:
img1 = img_as_float(io.imread('Image/bad2.png', as_gray=True))

print(img1)
# print(score)

[[1.         0.52033686 0.51162275 ... 0.51492549 0.50844353 0.51750078]
 [1.         0.51081922 0.4949149  ... 0.51197647 0.50609059 0.50256471]
 [1.         0.50353373 0.50225922 ... 0.44317216 0.46900902 0.49885059]
 ...
 [1.         0.41288941 0.42052588 ... 0.50033765 0.50342588 0.47479765]
 [1.         0.26533765 0.26222667 ... 0.50062039 0.50257765 0.49186078]
 [1.         0.36696157 0.34477137 ... 0.50818078 0.50286745 0.50788314]]


# Convert CSV to JSON 

In [ ]:
import csv 
import json 

In [ ]:
def make_Json(csvFilePath, jsonFilePath):
    with open(csvFilePath, "r") as f:
        reader = csv.reader(f)
        data = {"id:" , 
               "timestamp:", 
               "workflow:", 
               "locate:"}
        for row in reader: 
            #this is the actual process of creating the JSON file 
            key = ""
            data[key] = rows 
    with open(jsonFilePath, "w") as jsonf: 
        json.dump(data, jsonf, indent=4) #passing in the dictionary as the first argument, the name of the json file as 2nd arg

In [4]:
os.getcwd()

'C:\\Users\\alanx\\OneDrive\\Desktop\\keras\\IEEE'